// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: catly/object.proto

package catly

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectStatus int32

const (
	ObjectStatus_ObjectOK  ObjectStatus = 0
	ObjectStatus_ObjectERR ObjectStatus = 1
)

// Enum value maps for ObjectStatus.
var (
	ObjectStatus_name = map[int32]string{
		0: "ObjectOK",
		1: "ObjectERR",
	}
	ObjectStatus_value = map[string]int32{
		"ObjectOK":  0,
		"ObjectERR": 1,
	}
)

func (x ObjectStatus) Enum() *ObjectStatus {
	p := new(ObjectStatus)
	*p = x
	return p
}

func (x ObjectStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ObjectStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_catly_object_proto_enumTypes[0].Descriptor()
}

func (ObjectStatus) Type() protoreflect.EnumType {
	return &file_catly_object_proto_enumTypes[0]
}

func (x ObjectStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ObjectStatus.Descriptor instead.
func (ObjectStatus) EnumDescriptor() ([]byte, []int) {
	return file_catly_object_proto_rawDescGZIP(), []int{0}
}

type UploadObjectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *UploadObjectRequest) Reset() {
	*x = UploadObjectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catly_object_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectRequest) ProtoMessage() {}

func (x *UploadObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catly_object_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectRequest.ProtoReflect.Descriptor instead.
func (*UploadObjectRequest) Descriptor() ([]byte, []int) {
	return file_catly_object_proto_rawDescGZIP(), []int{0}
}

func (x *UploadObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadObjectRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadObjectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ObjectStatus `protobuf:"varint,1,opt,name=status,proto3,enum=catly.ObjectStatus" json:"status,omitempty"`
	Error  string       `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Url    string       `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *UploadObjectResponse) Reset() {
	*x = UploadObjectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_catly_object_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectResponse) ProtoMessage() {}

func (x *UploadObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catly_object_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectResponse.ProtoReflect.Descriptor instead.
func (*UploadObjectResponse) Descriptor() ([]byte, []int) {
	return file_catly_object_proto_rawDescGZIP(), []int{1}
}

func (x *UploadObjectResponse) GetStatus() ObjectStatus {
	if x != nil {
		return x.Status
	}
	return ObjectStatus_ObjectOK
}

func (x *UploadObjectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UploadObjectResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_catly_object_proto protoreflect.FileDescriptor

var file_catly_object_proto_rawDesc = []byte{
	0x0a, 0x12, 0x63, 0x61, 0x74, 0x6c, 0x79, 0x2f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x61, 0x74, 0x6c, 0x79, 0x22, 0x3d, 0x0a, 0x13, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x6b, 0x0a, 0x14, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x74, 0x6c, 0x79, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x2a, 0x2b, 0x0a, 0x0c, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x45,
	0x52, 0x52, 0x10, 0x01, 0x32, 0x4d, 0x0a, 0x06, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x43,
	0x0a, 0x06, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1a, 0x2e, 0x63, 0x61, 0x74, 0x6c, 0x79,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x74, 0x6c, 0x79, 0x2e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x70, 0x75, 0x72, 0x65, 0x68, 0x79, 0x70, 0x65, 0x72, 0x62, 0x6f, 0x6c, 0x65, 0x2f,
	0x63, 0x61, 0x74, 0x6c, 0x79, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x63,
	0x61, 0x74, 0x6c, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_catly_object_proto_rawDescOnce sync.Once
	file_catly_object_proto_rawDescData = file_catly_object_proto_rawDesc
)

func file_catly_object_proto_rawDescGZIP() []byte {
	file_catly_object_proto_rawDescOnce.Do(func() {
		file_catly_object_proto_rawDescData = protoimpl.X.CompressGZIP(file_catly_object_proto_rawDescData)
	})
	return file_catly_object_proto_rawDescData
}

var file_catly_object_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_catly_object_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_catly_object_proto_goTypes = []interface{}{
	(ObjectStatus)(0),            // 0: catly.ObjectStatus
	(*UploadObjectRequest)(nil),  // 1: catly.UploadObjectRequest
	(*UploadObjectResponse)(nil), // 2: catly.UploadObjectResponse
}
var file_catly_object_proto_depIdxs = []int32{
	0, // 0: catly.UploadObjectResponse.status:type_name -> catly.ObjectStatus
	1, // 1: catly.Object.Upload:input_type -> catly.UploadObjectRequest
	2, // 2: catly.Object.Upload:output_type -> catly.UploadObjectResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_catly_object_proto_init() }
func file_catly_object_proto_init() {
	if File_catly_object_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_catly_object_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadObjectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_catly_object_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadObjectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_catly_object_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catly_object_proto_goTypes,
		DependencyIndexes: file_catly_object_proto_depIdxs,
		EnumInfos:         file_catly_object_proto_enumTypes,
		MessageInfos:      file_catly_object_proto_msgTypes,
	}.Build()
	File_catly_object_proto = out.File
	file_catly_object_proto_rawDesc = nil
	file_catly_object_proto_goTypes = nil
	file_catly_object_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ObjectClient is the client API for Object service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObjectClient interface {
	// Uploads a file to the hosting service
	Upload(ctx context.Context, in *UploadObjectRequest, opts ...grpc.CallOption) (*UploadObjectResponse, error)
}

type objectClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectClient(cc grpc.ClientConnInterface) ObjectClient {
	return &objectClient{cc}
}

func (c *objectClient) Upload(ctx context.Context, in *UploadObjectRequest, opts ...grpc.CallOption) (*UploadObjectResponse, error) {
	out := new(UploadObjectResponse)
	err := c.cc.Invoke(ctx, "/catly.Object/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectServer is the server API for Object service.
type ObjectServer interface {
	// Uploads a file to the hosting service
	Upload(context.Context, *UploadObjectRequest) (*UploadObjectResponse, error)
}

// UnimplementedObjectServer can be embedded to have forward compatible implementations.
type UnimplementedObjectServer struct {
}

func (*UnimplementedObjectServer) Upload(context.Context, *UploadObjectRequest) (*UploadObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}

func RegisterObjectServer(s *grpc.Server, srv ObjectServer) {
	s.RegisterService(&_Object_serviceDesc, srv)
}

func _Object_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/catly.Object/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectServer).Upload(ctx, req.(*UploadObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Object_serviceDesc = grpc.ServiceDesc{
	ServiceName: "catly.Object",
	HandlerType: (*ObjectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upload",
			Handler:    _Object_Upload_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "catly/object.proto",
}
