name: CI

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: golang:1.17.0

    steps:
      - uses: actions/checkout@v2

      - name: Setup environment
        run: |
          apt-get update
          apt-get -y install protobuf-compiler make docker
          go install github.com/golang/protobuf/protoc-gen-go
          make generate
      - name: Test package
        run: go test -v -cover -covermode=atomic -race -coverprofile=coverage.out ./...
      - name: Build Server
        run: docker build -t catly-server .
      - name: Build client
        run:  go build -o grpc-upload cmd/client/main.go